[package]
name = "faer-sparse"
version = "0.16.0"
edition = "2021"
authors = ["sarah <>"]
description = "Basic linear algebra routines"
readme = "../../README.md"
repository = "https://github.com/sarah-ek/faer-rs/"
license = "MIT"
keywords = ["math", "matrix", "linear-algebra"]

[dependencies]
faer-entity = { workspace = true, default-features = false }

faer-core = { version = "0.16.0", default-features = false, path = "../faer-core" }
faer-cholesky = { version = "0.16.0", default-features = false, path = "../faer-cholesky" }
faer-qr = { version = "0.16.0", default-features = false, path = "../faer-qr" }
faer-lu = { version = "0.16.0", default-features = false, path = "../faer-lu" }

reborrow = { workspace = true }
dyn-stack = { workspace = true }
log = { workspace = true, optional = true }
rayon = { workspace = true }
bytemuck = { workspace = true }
pulp = { workspace = true, default-features = false}
coe-rs = { workspace = true }
dbgf = "0.1.1"

[features]
default = ["std", "rayon"]
std = [
  "faer-core/std",
  "faer-cholesky/std",
  "faer-qr/std",
  "faer-lu/std",
  "pulp/std",
]
rayon = [
  "std",
  "faer-core/rayon",
  "faer-cholesky/rayon",
  "faer-qr/rayon",
  "faer-lu/rayon",
]
nightly = [
  "faer-core/nightly",
  "faer-cholesky/nightly",
  "faer-qr/nightly",
  "faer-lu/nightly",
  "pulp/nightly",
]
perf-warn = ["log"]

[dev-dependencies]
criterion.workspace = true
rand = "0.8.5"
assert_approx_eq = "1.1.0"
dbgf = "0.1.1"
paste = "1.0.14"
matrix-market-rs = "0.1.3"
amd = "0.2.2"
colamd = { version = "0.1", features = ["i64"] }
num-complex.workspace = true
regex = "1.10.1"

[[bench]]
name = "cholesky"
harness = false

[[bench]]
name = "qr"
harness = false

[[bench]]
name = "lu"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
